# Generated by Django 3.1.4 on 2021-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('device', models.CharField(max_length=20)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
