# Generated by Django 3.1.4 on 2021-01-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_script'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
    ]
