# Generated by Django 3.1.4 on 2021-02-11 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0004_delete_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='device',
            new_name='deviceIMEI',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='timestamp',
            new_name='expiryDate',
        ),
        migrations.AddField(
            model_name='customer',
            name='scriptName',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
