# Generated by Django 3.1.4 on 2021-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0006_auto_20210211_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='scriptName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
