# Generated by Django 3.1.4 on 2021-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0007_auto_20210211_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luascript',
            name='app',
            field=models.FileField(default='', upload_to='shop'),
        ),
    ]
